//PatrickGVice
//Project Euler: Question 5
//
//What is the smallest positive number that is evenly divisible by all of the
//numbers from 1 to 20?
//The answer is: 232792560.

function primeList (limit){
  var prime = [];
  var isPrime;
  var j;

  prime.push(2);
  for (var i = 3; i <= limit; i+= 2){
    j = 0;
    isPrime = true;
    while (prime[j]*prime[j] <= i){
      if (i % prime[j] === 0){
          isPrime = false;
          break;
      }
      j++;
    }
    if (isPrime){
      prime.push(i);
    }
  }
  return prime;

};

// This takes all the primes generated by the primeList
// and then uses primes to add each number. Then mulitpulies them together
// to find the smallest number.

var lowestDivisor = function (){
  var divisor = 20;
  var prime = primeList(divisor);
  var result = 1;

  for (var i = 0; i < prime.length; i++){
    var a = Math.floor(Math.log(divisor) / Math.log(prime[i]));
    result = result * Math.pow(prime[i], a);
  }

  return result;
};



var answer = lowestDivisor();


console.log ("The answer is: "+answer);
